/**
 * Subtitle Master - ASS (Advanced SubStation Alpha) Generator
 * Generates rich, highly-compatible .ass subtitle files with style customization.
 */

import { formatSecondsToAss } from '../utils/time.js';

/**
 * Default ASS Style presets.
 */
export const ASS_PRESETS = {
  classicYellow: {
    name: '經典黃字黑邊',
    fontName: '微軟正黑體',
    fontSize: 52,
    primaryColor: '&H0000FFFF',   // Yellow (AABBGGRR: AA=00, BB=00, GG=FF, RR=FF)
    secondaryColor: '&H000000FF',
    outlineColor: '&H00000000',   // Black outline
    backColor: '&H80000000',      // Semi-transparent shadow
    bold: 1,
    italic: 0,
    borderStyle: 1,
    outline: 2.5,
    shadow: 1.2,
    alignment: 2, // Bottom center
    marginL: 40,
    marginR: 40,
    marginV: 45
  },
  modernWhite: {
    name: '簡約白字黑邊',
    fontName: '微軟正黑體',
    fontSize: 50,
    primaryColor: '&H00FFFFFF',   // White
    secondaryColor: '&H000000FF',
    outlineColor: '&H00000000',   // Black outline
    backColor: '&H80000000',
    bold: 1,
    italic: 0,
    borderStyle: 1,
    outline: 2.5,
    shadow: 1.0,
    alignment: 2,
    marginL: 40,
    marginR: 40,
    marginV: 45
  },
  netflixStyle: {
    name: 'Netflix 簡潔風格',
    fontName: '微軟正黑體',
    fontSize: 48,
    primaryColor: '&H00FFFFFF',
    secondaryColor: '&H000000FF',
    outlineColor: '&H00181818',
    backColor: '&HAA000000',
    bold: 0,
    italic: 0,
    borderStyle: 1,
    outline: 1.8,
    shadow: 2.0,
    alignment: 2,
    marginL: 50,
    marginR: 50,
    marginV: 50
  },
  animePink: {
    name: '櫻花粉動漫風',
    fontName: '微軟正黑體',
    fontSize: 54,
    primaryColor: '&H00E0A0FF',
    secondaryColor: '&H000000FF',
    outlineColor: '&H004A154B',
    backColor: '&H60000000',
    bold: 1,
    italic: 0,
    borderStyle: 1,
    outline: 3.0,
    shadow: 1.5,
    alignment: 2,
    marginL: 40,
    marginR: 40,
    marginV: 45
  },
  cyanGlow: {
    name: '科技青藍風',
    fontName: '微軟正黑體',
    fontSize: 52,
    primaryColor: '&H00FFFF00',   // Cyan
    secondaryColor: '&H000000FF',
    outlineColor: '&H001E1E2E',
    backColor: '&H80000000',
    bold: 1,
    italic: 0,
    borderStyle: 1,
    outline: 2.5,
    shadow: 1.5,
    alignment: 2,
    marginL: 40,
    marginR: 40,
    marginV: 45
  }
};

/**
 * Escapes text for ASS dialogue.
 * @param {string} text 
 * @returns {string}
 */
export function escapeAssText(text) {
  if (!text) return '';
  // Convert standard newlines to \N
  let escaped = text.replace(/\r\n|\r|\n/g, '\\N');
  // Escape curly braces that are not ASS tags
  escaped = escaped.replace(/\\\{/g, '{').replace(/\\\}/g, '}');
  escaped = escaped.replace(/{/g, '\\{').replace(/}/g, '\\}');
  return escaped;
}

/**
 * Generates ASS subtitle string.
 * @param {Array<{start: number, end: number, text: string, style?: string}>} cues 
 * @param {Object} [options={}]
 * @returns {string}
 */
export function generateAss(cues, options = {}) {
  if (!Array.isArray(cues) || cues.length === 0) {
    return '';
  }

  const title = options.title || 'Subtitle Master Converted';
  const resX = options.playResX || 1920;
  const resY = options.playResY || 1080;
  
  // Resolve style options or preset
  const stylePreset = options.preset && ASS_PRESETS[options.preset] ? ASS_PRESETS[options.preset] : ASS_PRESETS.classicYellow;
  const style = {
    ...stylePreset,
    ...options.style
  };

  let out = `[Script Info]
; Script generated by Subtitle Master
Title: ${title}
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
PlayResX: ${resX}
PlayResY: ${resY}

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,${style.fontName},${style.fontSize},${style.primaryColor},${style.secondaryColor},${style.outlineColor},${style.backColor},${style.bold ? -1 : 0},${style.italic ? -1 : 0},0,0,100,100,0,0,${style.borderStyle},${style.outline},${style.shadow},${style.alignment},${style.marginL},${style.marginR},${style.marginV},1
Style: Secondary,Helvetica,12,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,2,0,2,1,1,40,1
Style: LINE,LINE Seed TW_OTF Bold,48,&H0080FFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,1,0,1,2,0,2,1,1,40,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
`;

  const dialogueLines = [];
  for (let i = 0; i < cues.length; i++) {
    const cue = cues[i];
    const start = formatSecondsToAss(cue.start);
    const end = formatSecondsToAss(cue.end);
    const styleName = cue.style || 'Default';
    const text = escapeAssText(cue.text || '');

    dialogueLines.push(`Dialogue: 0,${start},${end},${styleName},,0,0,0,,${text}`);
  }

  return out + dialogueLines.join('\n') + '\n';
}
