/**
 * Subtitle Master - SSA (SubStation Alpha v4) Generator
 */

import { formatSecondsToAss } from '../utils/time.js';
import { escapeAssText } from './ass.js';

/**
 * @param {Array<{start: number, end: number, text: string}>} cues 
 * @param {Object} [options={}]
 * @returns {string}
 */
export function generateSsa(cues, options = {}) {
  if (!Array.isArray(cues) || cues.length === 0) {
    return '';
  }

  const title = options.title || 'Subtitle Master Converted SSA';
  const resX = options.playResX || 1280;
  const resY = options.playResY || 720;

  let out = `[Script Info]
; Script generated by Subtitle Master
Title: ${title}
ScriptType: v4.00
WrapStyle: 0
PlayResX: ${resX}
PlayResY: ${resY}

[V4 Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, TertiaryColour, BackColour, Bold, Italic, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, AlphaLevel, Encoding
Style: Default,微軟正黑體,40,65535,255,0,0,-1,0,1,2,1,2,30,30,30,0,1

[Events]
Format: Marked, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
`;

  const dialogueLines = [];
  for (let i = 0; i < cues.length; i++) {
    const cue = cues[i];
    const start = formatSecondsToAss(cue.start);
    const end = formatSecondsToAss(cue.end);
    const text = escapeAssText(cue.text || '');

    dialogueLines.push(`Dialogue: Marked=0,${start},${end},Default,,0000,0000,0000,,${text}`);
  }

  return out + dialogueLines.join('\n') + '\n';
}
